//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnamrDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adres
    {
        public Nullable<int> sysid { get; set; }
        public Nullable<int> idplace { get; set; }
        public string street { get; set; }
        public Nullable<byte> box { get; set; }
        public string housenmb { get; set; }
        public Nullable<int> postalindex { get; set; }
        public string numbertel { get; set; }
        public Nullable<System.DateTime> indt { get; set; }
        public Nullable<System.DateTime> outdt { get; set; }
        public Nullable<byte> doc_type { get; set; }
        public string src { get; set; }
        public byte ind { get; set; }
        public Nullable<System.DateTime> updt { get; set; }
        public int id { get; set; }
        public Nullable<int> usr { get; set; }
        public Nullable<byte> usr_add { get; set; }
        public Nullable<float> doze { get; set; }
        public Nullable<short> room { get; set; }
    
        public virtual id id1 { get; set; }
    }
}
