//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnamrDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adres_fm
    {
        public Nullable<int> sysid { get; set; }
        public Nullable<byte> idrelat { get; set; }
        public Nullable<int> idplace { get; set; }
        public Nullable<System.DateTime> indt { get; set; }
        public Nullable<byte> indf { get; set; }
        public Nullable<System.DateTime> outdt { get; set; }
        public Nullable<byte> outdf { get; set; }
        public string src { get; set; }
        public Nullable<byte> ind { get; set; }
        public Nullable<System.DateTime> updt { get; set; }
        public int id { get; set; }
        public Nullable<int> id_region { get; set; }
        public Nullable<int> id_area { get; set; }
    
        public virtual id id1 { get; set; }
    }
}
