//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnamrDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class edb
    {
        public int id { get; set; }
        public Nullable<int> sysid { get; set; }
        public string iin { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string midlname { get; set; }
        public Nullable<System.DateTime> birtdt { get; set; }
        public string src { get; set; }
        public Nullable<int> idnational { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> usr { get; set; }
    }
}
