//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnamrDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class id
    {
        public id()
        {
            this.adres = new HashSet<adres>();
            this.adres_fm = new HashSet<adres_fm>();
            this.biomaterials = new HashSet<biomaterials>();
            this.clc_diag = new HashSet<clc_diag>();
            this.doc_inf = new HashSet<doc_inf>();
            this.doze = new HashSet<doze>();
            this.educated = new HashSet<educated>();
            this.idead = new HashSet<idead>();
            this.lgm = new HashSet<lgm>();
            this.names = new HashSet<names>();
            this.relat = new HashSet<relat>();
            this.sich = new HashSet<sich>();
            this.trades = new HashSet<trades>();
        }
    
        public int sysid { get; set; }
        public Nullable<byte> gender { get; set; }
        public string stat_src { get; set; }
        public Nullable<System.DateTime> stat_dt { get; set; }
        public Nullable<System.DateTime> updt { get; set; }
        public string iin { get; set; }
        public Nullable<byte> usr { get; set; }
        public Nullable<byte> idnational { get; set; }
        public Nullable<byte> indelete { get; set; }
        public Nullable<int> sysid_duble { get; set; }
        public Nullable<int> idplace { get; set; }
        public Nullable<System.DateTime> birthdt { get; set; }
        public Nullable<byte> usr_add { get; set; }
        public Nullable<int> id_kagort { get; set; }
        public Nullable<byte> isstacionar { get; set; }
        public Nullable<int> idFather { get; set; }
        public Nullable<int> idMother { get; set; }
    
        public virtual ICollection<adres> adres { get; set; }
        public virtual ICollection<adres_fm> adres_fm { get; set; }
        public virtual ICollection<biomaterials> biomaterials { get; set; }
        public virtual ICollection<clc_diag> clc_diag { get; set; }
        public virtual ICollection<doc_inf> doc_inf { get; set; }
        public virtual ICollection<doze> doze { get; set; }
        public virtual ICollection<educated> educated { get; set; }
        public virtual ICollection<idead> idead { get; set; }
        public virtual ICollection<lgm> lgm { get; set; }
        public virtual ICollection<names> names { get; set; }
        public virtual ICollection<relat> relat { get; set; }
        public virtual ICollection<sich> sich { get; set; }
        public virtual ICollection<trades> trades { get; set; }
    }
}
