//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnamrDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class idead
    {
        public Nullable<int> sysid { get; set; }
        public string icd10 { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> deaddt { get; set; }
        public Nullable<byte> ind { get; set; }
        public Nullable<System.DateTime> updt { get; set; }
        public int id { get; set; }
        public Nullable<int> usr { get; set; }
        public string number { get; set; }
        public Nullable<byte> usr_add { get; set; }
        public string icd9 { get; set; }
    
        public virtual id id1 { get; set; }
    }
}
