//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnamrDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lgm
    {
        public int id { get; set; }
        public Nullable<int> sysid { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> meas_dt { get; set; }
        public Nullable<double> dicentrics { get; set; }
        public Nullable<double> fragments { get; set; }
        public Nullable<double> Translocation { get; set; }
        public Nullable<double> Ring_chromosome { get; set; }
        public string cg_prep { get; set; }
        public string relat { get; set; }
        public Nullable<System.DateTime> updt { get; set; }
        public Nullable<int> usr { get; set; }
        public Nullable<int> usr_add { get; set; }
    
        public virtual id id1 { get; set; }
    }
}
