//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnamrDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class relat
    {
        public Nullable<int> idsysid { get; set; }
        public Nullable<byte> idrelat { get; set; }
        public Nullable<int> idrelt { get; set; }
        public Nullable<int> dozes { get; set; }
        public Nullable<System.DateTime> updt { get; set; }
        public int id { get; set; }
        public Nullable<int> usr { get; set; }
        public Nullable<int> usr_add { get; set; }
    
        public virtual id id1 { get; set; }
    }
}
