//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnamrDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search
    {
        public int sysid { get; set; }
        public Nullable<byte> gender { get; set; }
        public string iin { get; set; }
        public string stat_src { get; set; }
        public Nullable<System.DateTime> stat_dt { get; set; }
        public Nullable<System.DateTime> updt { get; set; }
        public Nullable<byte> indelete { get; set; }
        public Nullable<System.DateTime> birthdt { get; set; }
        public Nullable<byte> usr_add { get; set; }
        public Nullable<byte> usr { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string midlname { get; set; }
        public byte ind { get; set; }
    }
}
