//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnamrDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sich
    {
        public int id { get; set; }
        public Nullable<int> sysid { get; set; }
        public Nullable<System.DateTime> meas_dt { get; set; }
        public Nullable<double> Cs137 { get; set; }
        public Nullable<double> error_cs137 { get; set; }
        public Nullable<double> I131 { get; set; }
        public Nullable<double> error_i131 { get; set; }
        public Nullable<double> Co60 { get; set; }
        public Nullable<double> error_co60 { get; set; }
        public Nullable<double> M54 { get; set; }
        public Nullable<double> error_m54 { get; set; }
        public Nullable<double> Cr51 { get; set; }
        public Nullable<double> error_cr51 { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> updt { get; set; }
        public Nullable<int> usr { get; set; }
        public Nullable<int> usr_add { get; set; }
    
        public virtual id id1 { get; set; }
    }
}
